### ISSUE TITLE
name of each script name

### ISSUE THREAD

**Issue by guiomar** [mne-tools/mne-bids-pipeline#349]
Hi! this is just a suggestion, please ignore it if it doesn't make sense. 
Would it be useful to name the scripts with something that indicate the step they belong to?
Currently they are like this:
![Captura de pantalla 2021-05-26 a las 20 28 56](https://user-images.githubusercontent.com/4451818/119712652-1c401900-be61-11eb-84fb-3a63b3ba23f8.png)

maybe inside preprocessing, they can be named: prep-01-xxxx, prep-02-xxxx, etc; 
inside sensor: sens-01-xxxx, sens-02-xxxx, etc
or similar, but to really know from the script name which step they belong to?

**Comment by hoechenberger** [comment]
I like this idea! Let's wait with the renaming until we have no PRs pending to be merged, as this change could cause endless merge conflicts

**Comment by sappelhoff** [comment]
I like this suggestion as well :+1:

**Comment by larsoner** [comment]
I'm not sure I see an advantage to adding the enclosing folder name to the script name. To me it adds redundancy without a clear benefit.

Perhaps more importantly, I'm not sure we need this / there is much priority for this since these are now private (prefixed by `_`) in a module-based package, so I'll close.
