### ISSUE TITLE
Check user defined variables in the config file

### ISSUE THREAD

**Issue by crsegerie** [mne-tools/mne-bids-pipeline#360]
We should take the time to check at the end of the configuration file that the user has not made any spelling mistakes or used variables defined in older versions of mne-bids-pipeline by checking the list of all defined variables. What do you think?

**Comment by hoechenberger** [comment]
Absolutely! The approach I discussed with @agramfort (due to an other issue, but it will resolve this problem as well) is switching to a Config class that can hold all the settings. Now, when parsing the user's configuration and trying to assign values to the config that are not supported by the Config class, we can emit an error message and abort. The only thing we'd need to discuss is how that would affect users introducing temporary variables and such in their config files. We could require users to `del`
everything that's not actually a setting at the end of their config. This is one of the drawbacks that comes with using Python code as the configuration "language". But the advantages surely outweigh the drawbacks for the time being, I believe!

**Comment by larsoner** [comment]
Setting the milestone to 0.2 for this, ideally using `pydantic` as mentioned in https://github.com/mne-tools/mne-bids-pipeline/issues/646#issuecomment-1308418144

**Comment by larsoner** [comment]
This has now been implemented!
