### ISSUE TITLE
                                                                                                                                                                                                                                                                                                                                                                              Bug when running the make_forward script on rest session

### ISSUE THREAD

**Issue by apmellot** [mne-tools/mne-bids-pipeline#443]
The issue comes from the fact that info is read from evoked file in this script ( ```info = mne.io.read_info(fname_evoked)```) but no evoked files are generated for rest session. 
@dengemann @agramfort @hoechenberger

**Comment by hoechenberger** [comment]
We could read it from Raw instead, I suppose?

**Comment by dengemann** [comment]
Yes. Caution: I suppose you took it from evoked because channels are picked
at that point. We may need to think about preserving / translating that
logic.

**Comment by larsoner** [comment]
I think this was fixed at some point

https://github.com/mne-tools/mne-bids-pipeline/blob/1cddb952b217ad2d1c8451823842faceeb3afd71/mne_bids_pipeline/scripts/source/_04_make_forward.py#L99

I'm not worried about the channel picking because it's fine for forward to have more channels than `evoked`, channels should be picked properly automatically when computing the inverse operator for example
