### ISSUE TITLE
Pipenv installation ERROR: Couldn't install package: mne-bids-pipeline

### ISSUE THREAD

**Issue by ktavabi** [mne-tools/mne-bids-pipeline#564]
`pipenv install` fails for `editable` installation of `mne-bids-pipeline` using `Pipfile` with `[packages]` including

`mne-bids-pipeline = {git = "https://github.com/mne-tools/mne-bids-pipeline.git", editable = true}`

> ERROR: mne-bids-pipeline from git+https://github.com/mne-tools/mne-bids-pipeline.git#egg=mne-bids-pipeline (from -r /var/folders/70/p04bhv6s0632wg81tpjy9x5h0000gn/T/pipenv-q75xr7ha-requirements/pipenv-yn7163hx-requirement.txt (line 1)) does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

I'm able to open PR to fix if 👍🏽

**Comment by hoechenberger** [comment]
Hello @ktavabi, currently, MNE-BIDS-Pipeline is not a proper package, so it cannot be installed like one. The currently imagined installation procedure is that users actually clone or download this repository and then use the `requirements.txt` file that ships with it to install all required dependencies. But there is no machinery to really "install" the pipeline itself, yet.

I started some work on this a while back, but it's gone stale since:
https://github.com/hoechenberger/mne-bids-pipeline-runner

Could you maybe explain your use case in a bit more detail? Why do you need to install the pipeline as a package?

Best wishes,
Richard

**Comment by ktavabi** [comment]
No particular use case. Just curious . Thx.
