### ISSUE TITLE
reject, reject_tmin, reject_tmax should get an epochs_* prefix as they only apply to epochs

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#695]
Thoughts on this one, @larsoner @agramfort?

**Comment by larsoner** [comment]
On the one hand I see the idea. On the other, if we start prepending the datatype that each var only applies to, our names will get quite long, e.g., `reader_extra_params->raw_ reader_extra_params`, `depth->inverse_depth`, etc. So to me it only makes sense to do it when it disambiguates, like the `method` for kwarg for `apply_inverse` is called `inverse_method` because `method` itself is ambiguous.

For me `decim` was strongly tied to epochs, but still made sense because there are other places you'd probably decimate (including during decoding). But it seems like `reject_tmin` and `reject_tmax` only really apply to epochs, and it doesn't seem ambiguous. And `reject` to me is closely associated with the `Epochs` constructor, even though there are some other places you can reject (e.g., during EOG or ECG projector calc).

**Comment by agramfort** [comment]
do you see any ambiguity with another context? if not I would say we are
good as is

**Comment by hoechenberger** [comment]
I suppose what we (I) really want is some sort of grouping or hierarchy in the settings. Some sort of namespaces.

**Comment by larsoner** [comment]
Namespaces are always a tradeoff (verbosity vs clarity, flat vs nested, etc.). Personally I'm okay with what we have currently in terms of readability. We could add namespaces but if we do it, we should do it for all variables rather than some. But this in turn would be an annoying backward compat break -- pretty much every existing `config.py` would need to change things like `l_freq` to `raw.l_freq` or `preprocessing.l_freq` or so, which is a pain. Granted we don't have a ton of end users, but I would even be a bit annoyed at having to make this change. Not to mention the internal code churn caused by such a change. And now users have to somehow create this `preprocessing` namespace so they can assign the attribute, rather than just having a Python variable directly. So -1 overall from me

**Comment by hoechenberger** [comment]
Yes, all very valid points @larsoner. Closing for now.
