### ISSUE TITLE
Something is wrong with the circleci-redirector workflow trigger

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#709]
We've got endless occurrences of (aborted?) workflow runs:

<img width="768" alt="Screenshot 2023-01-13 at 22 45 55" src="https://user-images.githubusercontent.com/2046265/212425174-13ba7d22-1622-4d74-9410-96d8c7898288.png">

**Comment by larsoner** [comment]
This might be normal. The redirector action runs for *any* repo status update, and there are probably 100 or so per PR? But most are skipped, which is what you see here. I think it might be working because some are green:

<img width="416" alt="Screenshot 2023-01-13 at 4 56 27 PM" src="https://user-images.githubusercontent.com/2365790/212426743-04618874-ceb2-4163-ad09-24407656cdb2.png">

**Comment by hoechenberger** [comment]
But is there no way to only let it run when actually needed? :)

**Comment by larsoner** [comment]
No

https://github.com/larsoner/circleci-artifacts-redirector-action/issues/27

**Comment by hoechenberger** [comment]
Bummer! But thanks for looking into the details of this! Amazing work!
