### ISSUE TITLE
Remove leading underscores from all module names?

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#870]
I believe we had initially introduced those underscores when we converted the pipeline from scripts that would be invoked directly by the user (or through a Makefile or something similar, I don't remember) to mere modules that are run through a parent script (now: `_run.py`). This was also before we turned the pipeline into an installable package with a CLI entry point.

Since the only supported use-case of the pipeline now is through CLI invocation, I'd be in favor of removing all those underscrores from all modules, as they're not really needed anymore.

WDYT?

**Comment by larsoner** [comment]
IIRC you can't have a Python module name start with a number

**Comment by larsoner** [comment]
... So for the steps at least I don't think we can. For stuff like `_run.py` I like that is clear that it's private currently, it's fairly standard scientific python ecosystem practice nowadays. Otherwise in the docs we'd need to make it clear that we are an exception to the rule: everything is considered private except the CLI, which people could miss. And then if we do remove the ones we can, it'll also be weird that only our step names do have underscores. So I think I'm -0.5 on removing them but can live with it if you want to

**Comment by hoechenberger** [comment]
Ok, this was just an idea. Let's leave it for now
