### ISSUE TITLE
STC saturated – rank problem?

### ISSUE THREAD

**Issue by SophieHerbst** [mne-tools/mne-bids-pipeline#905]
I am not happy with the stcs of some of my subjects, they look like the screenshot attached: at one moment in time there is very high activity everywhere, which messes up the scale. I remember that a similar outcome was caused by differences in rank between the cov used for whitening, and the rank given to compute the inverse. 

With cfg.noise_cov = 'rest', the following should read the info of the resting state run to compute the inverse.

 l. 52 in  source/_05_make_inverse.py
 in_files["info"] = bids_path.copy().update(**cfg.source_info_path_update)

I cannot figure out what the **cfg.source_info_path_update does. 
Thanks for any help!

<img width="1194" alt="Screenshot 2024-03-27 at 17 12 03" src="https://github.com/mne-tools/mne-bids-pipeline/assets/6408073/6120f409-3594-46bf-bd79-fccfcac0fdd7">

**Comment by larsoner** [comment]
Yes it's probably a rank mismatch between the empty room and your data. Are you using movement compensation? If subjects move a lot it could be an issue with our imperfect/incomplete capturing of movements during runs compared to empty rooms. Or you could be hitting https://github.com/mne-tools/mne-bids-pipeline/issues/760.

A long-term plan for at least some of this stuff could come out of https://github.com/mne-tools/mne-python/issues/4676, but even with that I don't think we're guaranteed to solve all issues.

I've been meaning to add something that allows computing the rank robustly from the epochs of interest -- in my work with infants who move a lot I almost always use something like:
```
rank = mne.compute_rank(epochs, tol=1e-3, tol_kind="relative")
```
and it has worked well. I propose we add something like:
```
rank_kind: Union[Literal["info"], Dict[str, Any]]
```
where the backward-compatible `rank_kind = "info"` is what we do currently (guess as best we can from `info`), otherwise allow a dict which is a set of `kwargs` to pass to `mne.compute_rank(epochs, **rank_kind)`. So in your case to follow my suggestion you would just add to your config:
```
rank_kind = dict(tol=1e-3, tol_kind="relative")
```
and then this would compute the rank from `epochs` and also pass `rank=...` to the covariance, inverse, and (possibly) decoding code.

**Comment by SophieHerbst** [comment]
thanks for the fast reply @larsoner!
would your solution still work if the rank of the resting state run is lower than that of the epochs (because there was one more bad sensor for instance)?

in my own code I did the following to prevent the problem:
- compute covariance from resting state with rank=info
- when computing the inverse, load the resting state again and pass its info (not the one of the epochs) to compute_inverse

**Comment by larsoner** [comment]
Ahh yes in principle you should probably compute the rank over whatever you're using to compute the covariance. So it should be computed in the `compute_covariance` step probably using whatever data you're computing the covariance over, which could be rest, empty room or task epochs. And in the case of a custom covariance note for people that the rank will be computed over the returned covariance which is generally less numerically accurate (but probably okay).

**Comment by SophieHerbst** [comment]
@larsoner it seems already the case that one can chose the file from which to read the info in source/05_make_inverse.py 
l. 51: in_files["info"] = bids_path.copy().update(**cfg.source_info_path_update)

I don't fully get how this works, but after setting in config: 
```
source_info_path_update = {'processing': 'clean',
                            'suffix': 'raw',
                            'task': 'noise'}
```

My stcs look fine. Is this the intended usage? 
If yes, wouldn't it make more sense to automatically use the info from the file from which the cov was computed?

**Comment by larsoner** [comment]
Yeah it seems like that would make sense. Not sure what the current behavior / default is for source_info_path_update is, seems like it should use the `noise_cov` if it can

**Comment by hoechenberger** [comment]
> Not sure what the current behavior / default is for source_info_path_update is, seems like it should use the `noise_cov` if it can

It reads the Info from the Evoked

**Comment by SophieHerbst** [comment]
I agree. I couldn't figure out what the default behavior does.

**Comment by hoechenberger** [comment]
So the solution would be to NOT use the Info from the Evoked if the noise cov was estimated from empty-room or resting-state data, do I understand this correctly?

**Comment by SophieHerbst** [comment]
yes, I think this is what causes the mismatch in ranks and the weird stcs

**Comment by hoechenberger** [comment]
> @hoechenberger if you can point me to where this happens, I can try to change it

Sorry, I can't give any useful advice for now, as I'm busy with other stuff … maybe by the end of the week, but I cannot promise anything!
