### ISSUE TITLE
pipeline fails if emptyroom data is missing cHPI

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-bids-pipeline#974]
When using `mf_filter_chpi=True` (or `mf_filter_chpi=None`), MNEBP will attempt to filter cHPI, but this causes a crash when the emptyroom data don't have cHPI channels enabled. In such cases what is the best approach?

- should `mne.preprocessing.maxwell_filter_prepare_emptyroom` try to copy the cHPI channels from the data file? That seems... complicated, given the unequal time domains of the two files.
- Should MNEBP be lenient for emptyroom files, maybe by calling `filter_chpi(..., allow_line_only=True)`?  (I can confirm that hacking this in does allow the pipeline step to succeed)
- should `mne.filter_chpi` be refactored to make its `recon` operator available, such that the `recon` could be computed on the raw reference data and applied to the emptyroom raw?

**Comment by larsoner** [comment]
> should mne.preprocessing.maxwell_filter_prepare_emptyroom try to copy the cHPI channels from the data file? That seems... complicated, given the unequal time domains of the two files.

This actually wouldn't in principle be too hard... except for sample rate mismatches. But given the cHPI are on or off a zero order hold interpolation could take care of that.

It's a bit of a weird case because it's really designed to remove the cHPI signals, but it will also distort the spectrum a bit. Hopefully in practice it won't make too much difference, though (aside from the line freqs!) because the frequencies tend to be quite high. So I think for for the empty room data for simplicity we should call `allow_line_only=True` as in the second suggestion above.
